/**
 * Vehicle reference data for cascading dropdowns.
 * Sourced from NHTSA vPIC API — top 20 makes in Canada.
 * This is bundled locally so dropdowns work instantly without network calls.
 */

export type Make = {
  slug: string;
  name: string;
  models: Model[];
};

export type Model = {
  slug: string;
  name: string;
};

export const MAKES: Make[] = [
  {
    slug: "toyota",
    name: "Toyota",
    models: [
      { slug: "corolla", name: "Corolla" },
      { slug: "camry", name: "Camry" },
      { slug: "rav4", name: "RAV4" },
      { slug: "highlander", name: "Highlander" },
      { slug: "4runner", name: "4Runner" },
      { slug: "tacoma", name: "Tacoma" },
      { slug: "tundra", name: "Tundra" },
      { slug: "prius", name: "Prius" },
      { slug: "supra", name: "Supra" },
      { slug: "c-hr", name: "C-HR" },
      { slug: "corolla-cross", name: "Corolla Cross" },
      { slug: "gr86", name: "GR86" },
      { slug: "bz4x", name: "bZ4X" },
      { slug: "crown", name: "Crown" },
      { slug: "grand-highlander", name: "Grand Highlander" },
      { slug: "sienna", name: "Sienna" },
      { slug: "sequoia", name: "Sequoia" },
      { slug: "venza", name: "Venza" },
      { slug: "gr-corolla", name: "GR Corolla" },
      { slug: "rav4-prime", name: "RAV4 Prime" },
    ],
  },
  {
    slug: "honda",
    name: "Honda",
    models: [
      { slug: "civic", name: "Civic" },
      { slug: "accord", name: "Accord" },
      { slug: "cr-v", name: "CR-V" },
      { slug: "hr-v", name: "HR-V" },
      { slug: "pilot", name: "Pilot" },
      { slug: "passport", name: "Passport" },
      { slug: "odyssey", name: "Odyssey" },
      { slug: "ridgeline", name: "Ridgeline" },
      { slug: "insight", name: "Insight" },
      { slug: "prologue", name: "Prologue" },
    ],
  },
  {
    slug: "ford",
    name: "Ford",
    models: [
      { slug: "f-150", name: "F-150" },
      { slug: "escape", name: "Escape" },
      { slug: "explorer", name: "Explorer" },
      { slug: "edge", name: "Edge" },
      { slug: "bronco", name: "Bronco" },
      { slug: "bronco-sport", name: "Bronco Sport" },
      { slug: "mustang", name: "Mustang" },
      { slug: "maverick", name: "Maverick" },
      { slug: "ranger", name: "Ranger" },
      { slug: "expedition", name: "Expedition" },
      { slug: "mustang-mach-e", name: "Mustang Mach-E" },
      { slug: "f-250", name: "F-250" },
      { slug: "f-350", name: "F-350" },
    ],
  },
  {
    slug: "chevrolet",
    name: "Chevrolet",
    models: [
      { slug: "silverado", name: "Silverado" },
      { slug: "equinox", name: "Equinox" },
      { slug: "traverse", name: "Traverse" },
      { slug: "tahoe", name: "Tahoe" },
      { slug: "suburban", name: "Suburban" },
      { slug: "colorado", name: "Colorado" },
      { slug: "camaro", name: "Camaro" },
      { slug: "corvette", name: "Corvette" },
      { slug: "blazer", name: "Blazer" },
      { slug: "trax", name: "Trax" },
      { slug: "trailblazer", name: "Trailblazer" },
      { slug: "bolt-ev", name: "Bolt EV" },
      { slug: "bolt-euv", name: "Bolt EUV" },
      { slug: "malibu", name: "Malibu" },
    ],
  },
  {
    slug: "hyundai",
    name: "Hyundai",
    models: [
      { slug: "tucson", name: "Tucson" },
      { slug: "santa-fe", name: "Santa Fe" },
      { slug: "elantra", name: "Elantra" },
      { slug: "sonata", name: "Sonata" },
      { slug: "kona", name: "Kona" },
      { slug: "palisade", name: "Palisade" },
      { slug: "venue", name: "Venue" },
      { slug: "ioniq-5", name: "Ioniq 5" },
      { slug: "ioniq-6", name: "Ioniq 6" },
      { slug: "santa-cruz", name: "Santa Cruz" },
      { slug: "accent", name: "Accent" },
      { slug: "ioniq-5-n", name: "Ioniq 5 N" },
    ],
  },
  {
    slug: "kia",
    name: "Kia",
    models: [
      { slug: "forte", name: "Forte" },
      { slug: "k5", name: "K5" },
      { slug: "sportage", name: "Sportage" },
      { slug: "sorento", name: "Sorento" },
      { slug: "telluride", name: "Telluride" },
      { slug: "seltos", name: "Seltos" },
      { slug: "soul", name: "Soul" },
      { slug: "niro", name: "Niro" },
      { slug: "stinger", name: "Stinger" },
      { slug: "ev6", name: "EV6" },
      { slug: "ev9", name: "EV9" },
      { slug: "rio", name: "Rio" },
      { slug: "carnival", name: "Carnival" },
    ],
  },
  {
    slug: "nissan",
    name: "Nissan",
    models: [
      { slug: "rogue", name: "Rogue" },
      { slug: "sentra", name: "Sentra" },
      { slug: "altima", name: "Altima" },
      { slug: "pathfinder", name: "Pathfinder" },
      { slug: "kicks", name: "Kicks" },
      { slug: "murano", name: "Murano" },
      { slug: "frontier", name: "Frontier" },
      { slug: "armada", name: "Armada" },
      { slug: "leaf", name: "Leaf" },
      { slug: "maxima", name: "Maxima" },
      { slug: "versa", name: "Versa" },
      { slug: "ariya", name: "Ariya" },
      { slug: "z", name: "Z" },
    ],
  },
  {
    slug: "mazda",
    name: "Mazda",
    models: [
      { slug: "mazda3", name: "Mazda3" },
      { slug: "cx-5", name: "CX-5" },
      { slug: "cx-30", name: "CX-30" },
      { slug: "cx-50", name: "CX-50" },
      { slug: "cx-90", name: "CX-90" },
      { slug: "cx-70", name: "CX-70" },
      { slug: "mx-5", name: "MX-5" },
      { slug: "cx-9", name: "CX-9" },
      { slug: "mazda6", name: "Mazda6" },
      { slug: "mx-30", name: "MX-30" },
    ],
  },
  {
    slug: "subaru",
    name: "Subaru",
    models: [
      { slug: "outback", name: "Outback" },
      { slug: "forester", name: "Forester" },
      { slug: "crosstrek", name: "Crosstrek" },
      { slug: "impreza", name: "Impreza" },
      { slug: "wrx", name: "WRX" },
      { slug: "legacy", name: "Legacy" },
      { slug: "ascent", name: "Ascent" },
      { slug: "brz", name: "BRZ" },
      { slug: "solterra", name: "Solterra" },
    ],
  },
  {
    slug: "volkswagen",
    name: "Volkswagen",
    models: [
      { slug: "jetta", name: "Jetta" },
      { slug: "tiguan", name: "Tiguan" },
      { slug: "atlas", name: "Atlas" },
      { slug: "golf", name: "Golf" },
      { slug: "taos", name: "Taos" },
      { slug: "id4", name: "ID.4" },
      { slug: "atlas-cross-sport", name: "Atlas Cross Sport" },
      { slug: "arteon", name: "Arteon" },
      { slug: "golf-gti", name: "Golf GTI" },
      { slug: "golf-r", name: "Golf R" },
      { slug: "id-buzz", name: "ID. Buzz" },
    ],
  },
  {
    slug: "bmw",
    name: "BMW",
    models: [
      { slug: "3-series", name: "3 Series" },
      { slug: "5-series", name: "5 Series" },
      { slug: "x3", name: "X3" },
      { slug: "x5", name: "X5" },
      { slug: "x1", name: "X1" },
      { slug: "4-series", name: "4 Series" },
      { slug: "7-series", name: "7 Series" },
      { slug: "x7", name: "X7" },
      { slug: "i4", name: "i4" },
      { slug: "ix", name: "iX" },
      { slug: "2-series", name: "2 Series" },
      { slug: "m3", name: "M3" },
      { slug: "m4", name: "M4" },
      { slug: "x2", name: "X2" },
      { slug: "x4", name: "X4" },
      { slug: "x6", name: "X6" },
      { slug: "i5", name: "i5" },
      { slug: "i7", name: "i7" },
    ],
  },
  {
    slug: "mercedes-benz",
    name: "Mercedes-Benz",
    models: [
      { slug: "c-class", name: "C-Class" },
      { slug: "e-class", name: "E-Class" },
      { slug: "glc", name: "GLC" },
      { slug: "gle", name: "GLE" },
      { slug: "a-class", name: "A-Class" },
      { slug: "cla", name: "CLA" },
      { slug: "glb", name: "GLB" },
      { slug: "gla", name: "GLA" },
      { slug: "s-class", name: "S-Class" },
      { slug: "gls", name: "GLS" },
      { slug: "eqb", name: "EQB" },
      { slug: "eqe", name: "EQE" },
      { slug: "eqs", name: "EQS" },
      { slug: "amg-gt", name: "AMG GT" },
    ],
  },
  {
    slug: "audi",
    name: "Audi",
    models: [
      { slug: "a4", name: "A4" },
      { slug: "a3", name: "A3" },
      { slug: "q5", name: "Q5" },
      { slug: "q7", name: "Q7" },
      { slug: "q3", name: "Q3" },
      { slug: "a5", name: "A5" },
      { slug: "a6", name: "A6" },
      { slug: "q8", name: "Q8" },
      { slug: "e-tron", name: "e-tron" },
      { slug: "e-tron-gt", name: "e-tron GT" },
      { slug: "rs-5", name: "RS 5" },
      { slug: "s4", name: "S4" },
      { slug: "q8-e-tron", name: "Q8 e-tron" },
    ],
  },
  {
    slug: "tesla",
    name: "Tesla",
    models: [
      { slug: "model-3", name: "Model 3" },
      { slug: "model-y", name: "Model Y" },
      { slug: "model-s", name: "Model S" },
      { slug: "model-x", name: "Model X" },
      { slug: "cybertruck", name: "Cybertruck" },
    ],
  },
  {
    slug: "jeep",
    name: "Jeep",
    models: [
      { slug: "grand-cherokee", name: "Grand Cherokee" },
      { slug: "wrangler", name: "Wrangler" },
      { slug: "cherokee", name: "Cherokee" },
      { slug: "compass", name: "Compass" },
      { slug: "gladiator", name: "Gladiator" },
      { slug: "grand-cherokee-l", name: "Grand Cherokee L" },
      { slug: "wagoneer", name: "Wagoneer" },
      { slug: "grand-wagoneer", name: "Grand Wagoneer" },
    ],
  },
  {
    slug: "ram",
    name: "Ram",
    models: [
      { slug: "1500", name: "1500" },
      { slug: "2500", name: "2500" },
      { slug: "3500", name: "3500" },
    ],
  },
  {
    slug: "gmc",
    name: "GMC",
    models: [
      { slug: "sierra", name: "Sierra" },
      { slug: "terrain", name: "Terrain" },
      { slug: "acadia", name: "Acadia" },
      { slug: "yukon", name: "Yukon" },
      { slug: "canyon", name: "Canyon" },
      { slug: "hummer-ev", name: "Hummer EV" },
    ],
  },
  {
    slug: "lexus",
    name: "Lexus",
    models: [
      { slug: "rx", name: "RX" },
      { slug: "nx", name: "NX" },
      { slug: "is", name: "IS" },
      { slug: "es", name: "ES" },
      { slug: "ux", name: "UX" },
      { slug: "gx", name: "GX" },
      { slug: "lx", name: "LX" },
      { slug: "tx", name: "TX" },
      { slug: "rz", name: "RZ" },
      { slug: "lc", name: "LC" },
    ],
  },
  {
    slug: "acura",
    name: "Acura",
    models: [
      { slug: "tlx", name: "TLX" },
      { slug: "rdx", name: "RDX" },
      { slug: "mdx", name: "MDX" },
      { slug: "integra", name: "Integra" },
      { slug: "zdx", name: "ZDX" },
    ],
  },
  {
    slug: "dodge",
    name: "Dodge",
    models: [
      { slug: "charger", name: "Charger" },
      { slug: "durango", name: "Durango" },
      { slug: "challenger", name: "Challenger" },
      { slug: "hornet", name: "Hornet" },
    ],
  },
];

/** Years available for selection (current + recent) */
export const YEARS = [2026, 2025, 2024, 2023, 2022, 2021, 2020];
